### ISSUE TITLE
NoMethodError: undefined method each

### ISSUE THREAD

**Issue by aliabbasrizvi** [GoogleCloudPlatform/google-fluentd#360]
I am trying to set up the agent in my container (using debian:10.10). 

Every time a message is sent it fails as follows:

```
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: parsing config file is succeeded path="/etc/google-fluentd/google-fluentd.conf"
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-concat' version '2.4.0'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-detect-exceptions' version '0.0.12'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-google-cloud' version '0.12.0'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.5.2'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-multi-format-parser' version '1.0.0'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.4.0'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-record-modifier' version '2.0.1'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-record-reformer' version '0.9.1'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.10'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.5'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluent-plugin-webhdfs' version '1.2.3'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluentd' version '1.13.3'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: gem 'fluentd' version '1.11.5'
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: use_metadata_service is false; not detecting platform
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: using configuration file: <ROOT>
fluentd_1     |   <source>
fluentd_1     |     @type forward
fluentd_1     |   </source>
fluentd_1     |   <filter **>
fluentd_1     |     @type add_insert_ids
fluentd_1     |     @log_level "debug"
fluentd_1     |   </filter>
fluentd_1     |   <filter **>
fluentd_1     |     @type record_transformer
fluentd_1     |     enable_ruby true
fluentd_1     |     <record>
fluentd_1     |       timestamp ${ require 'time'; Time.now.utc.iso8601(3) }
fluentd_1     |     </record>
fluentd_1     |   </filter>
fluentd_1     |   <label @FLUENT_LOG>
fluentd_1     |     <match fluent.*>
fluentd_1     |       @type stdout
fluentd_1     |     </match>
fluentd_1     |   </label>
fluentd_1     |   <match my_service>
fluentd_1     |     @type google_cloud
fluentd_1     |     @log_level "debug"
fluentd_1     |     use_metadata_service false
fluentd_1     |     <buffer>
fluentd_1     |       flush_mode interval
fluentd_1     |       retry_type exponential_backoff
fluentd_1     |     </buffer>
fluentd_1     |   </match>
fluentd_1     | </ROOT>
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: starting fluentd-1.13.3 pid=33 ruby="2.6.5"
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: spawn command to main:  cmdline=["/opt/google-fluentd/embedded/bin/ruby", "-Eascii-8bit:ascii-8bit", "/usr/sbin/google-fluentd", "--under-supervisor"]
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: adding match in @FLUENT_LOG pattern="fluent.*" type="stdout"
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: adding filter pattern="**" type="add_insert_ids"
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: adding filter pattern="**" type="record_transformer"
fluentd_1     | 2021-09-08 20:55:22 +0000 [info]: adding match pattern="my_service" type="google_cloud"
fluentd_1     | 2021-09-08 20:55:23 +0000 [info]: #0 use_metadata_service is false; not detecting platform
fluentd_1     | 2021-09-08 20:55:23 +0000 [info]: adding source type="forward"
fluentd_1     | 2021-09-08 20:55:23 +0000 [info]: #0 starting fluentd worker pid=39 ppid=33 worker=0
fluentd_1     | 2021-09-08 20:55:23 +0000 [info]: #0 Started the add_insert_ids plugin with logging.googleapis.com/insertId as the insert ID key.
fluentd_1     | 2021-09-08 20:55:23 +0000 [info]: #0 Initialized the insert ID key to h43tnsm3mxde57v33.
fluentd_1     | 2021-09-08 20:55:23 +0000 [debug]: #0 buffer started instance=47011979872020 stage_size=0 queue_size=0
fluentd_1     | 2021-09-08 20:55:23 +0000 [info]: #0 listening port port=24224 bind="0.0.0.0"
fluentd_1     | 2021-09-08 20:55:23 +0000 [info]: #0 fluentd worker is now running worker=0
fluentd_1     | 2021-09-08 20:55:23.233380300 +0000 fluent.info: {"pid":39,"ppid":33,"worker":0,"message":"starting fluentd worker pid=39 ppid=33 worker=0"}
fluentd_1     | 2021-09-08 20:55:23.233515000 +0000 fluent.info: {"message":"Started the add_insert_ids plugin with logging.googleapis.com/insertId as the insert ID key."}
fluentd_1     | 2021-09-08 20:55:23.233567900 +0000 fluent.info: {"message":"Initialized the insert ID key to h43tnsm3mxde57v33."}
fluentd_1     | 2021-09-08 20:55:23.233829700 +0000 fluent.debug: {"instance":47011979872020,"stage_size":0,"queue_size":0,"message":"buffer started instance=47011979872020 stage_size=0 queue_size=0"}
fluentd_1     | 2021-09-08 20:55:23.235076200 +0000 fluent.info: {"port":24224,"bind":"0.0.0.0","message":"listening port port=24224 bind=\"0.0.0.0\""}
fluentd_1     | 2021-09-08 20:55:23.235525200 +0000 fluent.info: {"worker":0,"message":"fluentd worker is now running worker=0"}
fluentd_1     | 2021-09-08 20:55:23 +0000 [debug]: #0 enqueue_thread actually running
fluentd_1     | 2021-09-08 20:55:23 +0000 [debug]: #0 flush_thread actually running
fluentd_1     | 2021-09-08 20:55:23.735294400 +0000 fluent.debug: {"message":"enqueue_thread actually running"}
fluentd_1     | 2021-09-08 20:55:23.736058700 +0000 fluent.debug: {"message":"flush_thread actually running"}
fluentd_1     | 2021-09-08 20:55:44 +0000 [info]: #0 disable filter chain optimization because [Fluent::Plugin::RecordTransformerFilter] uses `#filter_stream` method.
fluentd_1     | 2021-09-08 20:55:44.181471800 +0000 fluent.info: {"message":"disable filter chain optimization because [Fluent::Plugin::RecordTransformerFilter] uses `#filter_stream` method."}
fluentd_1     | 2021-09-08 20:56:46 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=NoMethodError error="undefined method `each' for nil:NilClass"
fluentd_1     | 2021-09-08 20:56:46.303820400 +0000 fluent.warn: {"error":"#<NoMethodError: undefined method `each' for nil:NilClass>","message":"got unrecoverable error in primary and no secondary error_class=NoMethodError error=\"undefined method `each' for nil:NilClass\""}
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:49:in `block in call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:48:in `tap'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:48:in `call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:19:in `evaluate'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:10:in `block in call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `each'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `inject'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:50:in `compile_fragment'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:14:in `block in call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `each'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable.rb:68:in `representable_map!'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable.rb:56:in `create_representation_with'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/hash.rb:37:in `to_hash'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/serializer.rb:45:in `block in <module:Representable>'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:19:in `evaluate'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:10:in `block in call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `each'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `inject'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:50:in `compile_fragment'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:14:in `block in call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `each'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable.rb:68:in `representable_map!'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable.rb:56:in `create_representation_with'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/hash.rb:37:in `to_hash'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/serializer.rb:45:in `block in <module:Representable>'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:19:in `evaluate'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:10:in `block in call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `each'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `inject'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:40:in `block in call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:39:in `each'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:39:in `each_with_index'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:39:in `call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:19:in `evaluate'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:10:in `block in call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `each'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `inject'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/pipeline.rb:9:in `call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:50:in `compile_fragment'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:14:in `block in call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `each'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/binding.rb:12:in `call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable.rb:68:in `representable_map!'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable.rb:56:in `create_representation_with'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/hash.rb:37:in `to_hash'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/representable-3.1.1/lib/representable/json.rb:42:in `to_json'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/google-api-client-0.30.8/lib/google/apis/core/api_command.rb:64:in `prepare!'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/google-api-client-0.30.8/lib/google/apis/core/http_command.rb:99:in `execute'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/google-api-client-0.30.8/lib/google/apis/core/base_service.rb:360:in `execute_or_queue_command'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/google-api-client-0.30.8/generated/google/apis/logging_v2/service.rb:695:in `write_entry_log_entries'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluent-plugin-google-cloud-0.12.0/lib/fluent/plugin/out_google_cloud.rb:1013:in `write_request_via_rest'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluent-plugin-google-cloud-0.12.0/lib/fluent/plugin/out_google_cloud.rb:789:in `call'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluent-plugin-google-cloud-0.12.0/lib/fluent/plugin/out_google_cloud.rb:789:in `write'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/compat/output.rb:131:in `write'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:1138:in `try_flush'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:1450:in `flush_thread_run'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin/output.rb:462:in `block (2 levels) in start'
fluentd_1     |   2021-09-08 20:56:46 +0000 [warn]: #0 /opt/google-fluentd/embedded/lib/ruby/gems/2.6.0/gems/fluentd-1.13.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
fluentd_1     | 2021-09-08 20:56:46 +0000 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_2ac1d4592dcc/5cb821b1644efb700543127c4850c620.log
fluentd_1     | 2021-09-08 20:56:46.305762500 +0000 fluent.warn: {"message":"bad chunk is moved to /tmp/fluent/backup/worker0/object_2ac1d4592dcc/5cb821b1644efb700543127c4850c620.log"}
```

Am I missing something in the config here? Would appreciate any feedback.

**Comment by aliabbasrizvi** [comment]
Tried with modified configuration. Still no luck. Any help will be appreciated.

```
<source>
  @type forward
</source>

<filter **>
  @type add_insert_ids
  @log_level debug
</filter>

<filter **>
  @type parser
  format json
  key_name log
  reserve_data true
  emit_invalid_record_to_error false
</filter>

<filter **>
  @type record_transformer
  enable_ruby true
  time_key timestamp
  remove_keys log
  <record>
    timestamp ${ require 'time'; Time.now.utc.iso8601(3) }
    message ${record["log"]}    
  </record>
</filter>

<label @FLUENT_LOG>
  <match fluent.*>
    @type stdout
  </match>
</label>

<match my_service>
  @type google_cloud
  use_metadata_service false
</match>
```

**Comment by aliabbasrizvi** [comment]
Ended up moving to use fluent-bit. Closing this issue.
